// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZQ0ztBNIxvgRnAjhYdH38wbrhEALkYCo',
    appId: '1:179271894511:web:7994791722c36fbc36e21a',
    messagingSenderId: '179271894511',
    projectId: 'kangsayur-b8760',
    authDomain: 'kangsayur-b8760.firebaseapp.com',
    storageBucket: 'kangsayur-b8760.appspot.com',
    measurementId: 'G-L2LGGKG47P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoj6GYOgws4NNvQnRr4vYMVVSRmePlHmw',
    appId: '1:179271894511:android:236a0275fc07257e36e21a',
    messagingSenderId: '179271894511',
    projectId: 'kangsayur-b8760',
    storageBucket: 'kangsayur-b8760.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB2BZ5MIfcxvI7TzU9ZE_5CceLblu3KQ4',
    appId: '1:179271894511:ios:9056325a9e333dfc36e21a',
    messagingSenderId: '179271894511',
    projectId: 'kangsayur-b8760',
    storageBucket: 'kangsayur-b8760.appspot.com',
    iosClientId: '179271894511-kq3v0gqbsjh9idr6ehk093kd7v07uvj6.apps.googleusercontent.com',
    iosBundleId: 'com.example.kangsayur',
  );
}
